# Configure main menu and social menu
[[main]]
identifier = "About"
name = "About"
url = "/about"
[main.params]
icon = "user"
newtab = false

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/kuouu"
[social.params]
icon = "brand-github"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://linkedin.com/in/kuouu"
[social.params]
icon = "brand-linkedin"

[[social]]
identifier = "rss"
name = "RSS"
url = "https://blog.kuouu.tw/index.xml"
[social.params]
icon = "rss"
