# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon = "/img/favicon.ico"

[footer]
since = 2024
customText = ""

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006"

[sidebar]
emoji = "😎"
subtitle = "hi!"

[sidebar.avatar]
enabled = true
local = false
src = "https://avatars.githubusercontent.com/u/20458463?v=4"

[article]
headingAnchor = false
math = false
readingTime = false

[article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"

## Widgets

[[widgets.page]]
type = "toc"

[opengraph.twitter]
site = ""
card = "summary_large_image"

[defaultImage.opengraph]
enabled = false
local = false
src = ""

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

## Comments
[comments]
enabled = true
provider = "giscus"

[comments.giscus]
repo = "kuouu/blog"
repoID = "R_kgDOHX1iZQ"
category = "Announcements"
categoryID = "DIC_kwDOHX1iZc4CcWpY"
mapping = "title"
lightTheme = "light"
darkTheme = "noborder_gray"
reactionsEnabled = 1
emitMetadata = 0
