module:
    hugoVersion:
        extended: true
        min: "0.87.0"

title: uuBlog
description: kuouu's blog

googleAnalytics: G-D9WP3KE61L

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon: "/img/favicon.ico"

    footer:
        since: 2024
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        compact: false
        emoji: 🥺
        subtitle: hi!
        avatar:
            enabled: true
            local: false
            src: https://avatars.githubusercontent.com/u/20458463?v=4

    article:
        math: true
        toc: true
        readingTime: false
        license:
            enabled: false
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: true
        provider: giscus

        giscus:
            repo: kuouu/blog
            repoID: R_kgDOHX1iZQ
            category: Announcements
            categoryID: DIC_kwDOHX1iZc4CcWpY
            mapping: title
            strict: 0
            lightTheme: light
            darkTheme: noborder_gray
            reactionsEnabled: 1
            emitMetadata: 0
            inputPosition: bottom
            lang: zh-TW

    widgets:
        homepage: []
        page: []

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true
    render:
        image:
            externalLink:
                enabled: true
